import type { Metadata } from "next";

import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

import { AuthProvider } from "@/contexts/AuthContext";

export const metadata: Metadata = {
  title: "SPL Management System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <nav>
            <div>
              <ul>
                <li>students</li>
                <li>teachers</li>
              </ul>
            </div>
          </nav>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
